spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workattendance?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: flw111225
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 43.139.93.123
    port: 6379
    database: 0
    timeout: 5000
    password: flw111225
  lettuce:
     pool:
       max-wait: -1
       max-idle: 5
       min-idle: 0
       max-active: 20
# 应用名称
spring.application.name: KeepOnAttence
  # 应用服务 WEB 访问端口
server.port: 8080
  # 数据源名称
spring.datasource.name: defaultDataSource

#mybatis全局配置文件
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

files:
  upload:
    path: E:/KeepOnWorkFileResource/files/



